
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    http: true
    tlsacme: false

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

spring-testing:
  replicaCount: 1
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent

  # define environment variables here as a map of key: value
  env:
    WEATHER_API_KEY: "49bdd296a3e91ef8d6a69c8b33c4b7fa"
    DB_PORT: "5432"
    DB_NAME: "postgres"
    DB_USER: "postgres"
    DB_PASSWORD: "password"

spring-testing-db:
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: password